spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            pool-name: hikari-pool
            catalog: notice
            minimum-idle: 5
            maximum-pool-size: 100
            data-source-properties:
                idleTimeout: 600000
                maxLifetime: 1800000
                minimumIdle: 5
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            connection-test-query: select 1
            auto-commit: true
